apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice-deployment
spec:
  selector:
    matchLabels:
      app: apiservice
      type: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: apiservice
        type: backend
    spec:
      containers:
      - name: apiservice-container
        image: REPLACE_ME_WITH_YOUR_IMAGE_PATH  # Fox example: ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9797
      imagePullSecrets:
        - name: us-west-2-ecr-registry