apiVersion: v1
kind: Service
metadata:
  name: apiservice-service
spec:
  ports: 
    - protocol: TCP
      targetPort: 9797
      port: 80
  selector:
    app: apiservice
    type: backend
  type: LoadBalancer